### PR TITLE
Try to create home directory on login (#37)

### PR DESCRIPTION
**Pull request by andersevenrud**

### CODE REVIEW

**Comment by RaufSSen** [comment]
`const consola = require('consola');
const logger = consola.withTag('Auth');
const nullAdapter = require('./adapters/auth/null.js');

/**
 * Authentication Handler
 */
class Auth {

  /**
   * Creates a new instance
   * @param {Core} core Core instance reference
   * @param {Object} [options={}] Service Provider arguments
   */
  constructor(core, options = {}) {
    const {requiredGroups, denyUsers} = core.configuration.auth;

    this.core = core;
    this.options = {
      adapter: nullAdapter,
      requiredGroups,
      denyUsers,
      ...options
    };

    try {
      this.adapter = this.options.adapter(core, this.options.config);
    } catch (e) {
      this.core.logger.warn(e);
      this.adapter = nullAdapter(core, this.options.config);
    }
  }

  /**
   * Destroys instance
   */
  destroy() {
    if (this.adapter.destroy) {
      this.adapter.destroy();
    }
  }

  /**
   * Initializes adapter
   */
  async init() {
    if (this.adapter.init) {
      return this.adapter.init();
    }

    return true;
  }

  /**
   * Performs a login request
   * @param {Object} req HTTP request
   * @param {Object} res HTTP response
   */
  async login(req, res) {
    const result = await this.adapter.login(req, res);

    if (result) {
      const profile = this.createUserProfile(req.body, result);
      if (profile && this.checkLoginPermissions(profile)) {
        await this.createHomeDirectory(profile, req, res);
        req.session.user = profile;
        req.session.save(() => res.status(200).json(profile));
        return;
      }
    }

    res.status(403)
      .json({error: 'Invalid login or permission denied'});
  }

  /**
   * Performs a logout request
   * @param {Object} req HTTP request
   * @param {Object} res HTTP response
   */
  async logout(req, res) {
    await this.adapter.logout(req, res);

    try {
      req.session.destroy();
    } catch (e) {
      logger.warn(e);
    }

    res.json({});
  }

  /**
   * Performs a register request
   * @param {Object} req HTTP request
   * @param {Object} res HTTP response
   */
  async register(req, res) {
    if (this.adapter.register) {
      const result = await this.adapter.register(req, res);

      return res.json(result);
    }

    return res.status(403)
      .json({error: 'Registration unavailable'});
  }

  /**
   * Checks if login is allowed for this user
   * @param {object} profile User profile
   * @return {boolean}
   */
  checkLoginPermissions(profile) {
    const {requiredGroups, denyUsers} = this.options;

    if (denyUsers.indexOf(profile.username) !== -1) {
      return false;
    }

    if (requiredGroups.length > 0) {
      const passes = requiredGroups.every(name => {
        return profile.groups.indexOf(name) !== -1;
      });

      return passes;
    }

    return true;
  }

  /**
   * Creates user profile object
   * @param {object} fields Input fields
   * @param {object} result Login result
   * @return {object}
   */
  createUserProfile(fields, result) {
    const ignores = ['password'];
    const required = ['username', 'id'];
    const template = {
      id: 0,
      username: fields.username,
      name: fields.username,
      groups: this.core.config('auth.defaultGroups', [])
    };

    const missing = required
      .filter(k => typeof result[k] === 'undefined');

    if (missing.length) {
      logger.warn('Missing user attributes', missing);
    } else {
      const values = Object.keys(result)
        .filter(k => ignores.indexOf(k) === -1)
        .reduce((o, k) => ({...o, [k]: result[k]}), {});

      return {...template, ...values};
    }

    return false;
  }
  /**
   * Tries to create home directory for a user
   * @param {object} profile User profile
   */
  async createHomeDirectory(profile) {
    try {
      const homeDir = await this
        .core
        .make('osjs/vfs')
        .realpath('home:/', profile);

      await fs.ensureDir(homeDir);
    } catch (e) {
      console.warn('Failed trying to make home directory for', profile.username);
    }
  }
}
module.exports = Auth;`

My auth.js file with changes. What is wrong?

**Comment by andersevenrud** [comment]
How did you apply these changes ? Like did you check out a local version of the server, or something else ?

**Comment by RaufSSen** [comment]
Sorry but I changed npm repo.

:D

**Comment by andersevenrud** [comment]
And how exactly did you do it ?

**Comment by RaufSSen** [comment]
simple just go to node_modules\@osjs\

d:

**Comment by andersevenrud** [comment]
OK. This is the recommended way of changing *out* a npm repo https://manual.os-js.org/v3/guide/modules/. Changes inside `node_modules` are not persistent.

Anyways, if you restarted the server afterwards this should have taken effect. You don't get any warnings or errors in the server logs ?

If you don't you can probably just add some debugging into the new class method that was added to see if it actually runs.

**Comment by RaufSSen** [comment]
OK, let's see.

**Comment by RaufSSen** [comment]
It seems code is triggering when someone login.

**Comment by RaufSSen** [comment]
Sorry my bad, I just didn't add `const fs = require('fs-extra');` start of the code.

**Pull request merged**
