### PR TITLE
Supporting utf8 character for downloading files

### PR DESCRIPTION
**Pull request by miladhashemi**
#49

### CODE REVIEW

**Comment by andersevenrud** [comment]
Does this work in all common browsers today ?

The last time I did something like this it broke Firefox and Safari, but maybe those days are past :)

**Comment by miladhashemi** [comment]
I tested in on chrome and firefox. I didn't have safari to test.

**Comment by miladhashemi** [comment]
> Does this work in all common browsers today ?

I tested it today, it doesn't work in all common browser.It just works on mozilla firefox

**Comment by miladhashemi** [comment]
> I tested it today, it doesn't work in all common browser.It just works on mozilla firefox.

Oh I'm sorry. I checked `monster-adapter`, I found yesterday I had overridden it, that cause it doesn't work today. It works on mozilla and chrome.. I must tested it on safari!

**Comment by andersevenrud** [comment]
My Macbook died, so I currently don't have a OSX Machine to test on, but I think I can launch it up in a VM on my workstation :thinking:

**Comment by miladhashemi** [comment]
I install MacOS Big Sur on my PC. With safari 14.0.3. It worked fine. 
image

**Comment by andersevenrud** [comment]
Great! Thanks :)

**Pull request merged**
