### PR TITLE
Fix annotation of VFS search function

### PR DESCRIPTION
**Pull request by mahsashadi**
It seems search function does not return boolean.

### CODE REVIEW

**Review by ajmeese7 — APPROVED** [review]
Looks good to me, it might benefit by having an actual type for the array instead of just saying that it's an array of objects, but that's up to @andersevenrud. Good catch 👍🏼

**Comment by andersevenrud** [comment]
> having an actual type

That would be preferable. I checked, and this package don't have many of them documented.

Also, a lot of the annotations in this file is invalid. Should actually be `Promise<T>` for pretty much all of them :sweat_smile:

**Comment by andersevenrud** [comment]
A good commit message for this would be: `docs(vfs): update search function annotation`.

This repo uses https://www.conventionalcommits.org/en/v1.0.0/

**Comment by mahsashadi** [comment]
> A good commit message for this would be: `docs(vfs): update search function annotation`.
> 
> This repo uses https://www.conventionalcommits.org/en/v1.0.0/

Done
@andersevenrud

**Comment by andersevenrud** [comment]
> Done

Could you make it a `Promise<Object>` ?

**Pull request merged**
