### PR TITLE
fix(vfs): race condition on temp file cleanup

### PR DESCRIPTION
**Pull request by andersevenrud**
There was a race condition relating to streams in the VFS pipeline that could lead to unhandled rejection whenever a cleanup is performed on an endpoint with pre-check errors (like readonly).

Fixes https://github.com/os-js/OS.js/issues/840

### CODE REVIEW

**Comment by andersevenrud** [comment]
@maryam4s26 could you try this PR and checks if this fixes your errors in https://github.com/os-js/OS.js/issues/840 ?

**Comment by maryam4s26** [comment]
hi @andersevenrud 
I checked this PP. it is ok.
I have also made some changes and sent my [PP](https://github.com/os-js/osjs-server/pull/78).
If possible, check it as well.

**Comment by maryam4s26** [comment]
> @maryam4s26 could you try this PR and checks if this fixes your errors in [os-js/OS.js#840](https://github.com/os-js/OS.js/issues/840) ?

hi @andersevenrud
I checked this PP. it is ok.

**Comment by maryam4s26** [comment]
> @maryam4s26 could you try this PR and checks if this fixes your errors in [os-js/OS.js#840](https://github.com/os-js/OS.js/issues/840) ?

hi @andersevenrud
I checked this PR. it is ok.

**Pull request merged**
